Try caching with branch name

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,7 +25,9 @@ jobs:
         uses: actions/cache/restore@v4
         id: cache
         with:
-          key: ${{ runner.os }}
+          key: ${{ runner.os }}-${{ github.ref_name	}}
+          restore-keys: |
+            ${{ runner.os }}-main
           path: ${{github.workspace}}/vcpkg-binary-cache
 
 # -------------------------------------------------------------------
@@ -49,9 +51,10 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}
         if: steps.cache.outputs.cache-hit
+        shell: bash
         # Using `--repo` makes it so that this step doesn't require checking out the
-        # repo first.
-        run: gh cache delete --repo ${{ github.repository }} ${{ steps.cache.outputs.cache-primary-key }}
+        # repo first. This will fail for PRs, so use '|| true' to never fail this step
+        run: gh cache delete --repo ${{ github.repository }} ${{ steps.cache.outputs.cache-primary-key }} || true
 
       - name: Save cache
         uses: actions/cache/save@v4
